apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  labels:
     role: web
     version: v1
spec:
  containers:
    - name: app
      image: nginx:1.9.5
      ports:
      - containerPort: 80
        protocol: TCP
