apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: nginx-deployment
  labels:
     role: web
spec:
  replicas: 2
  selector:
    matchLabels:
      role: web 
  template: 
    metadata:
      labels:
        role: web
    spec:
      containers:
        - name: app
          image: nginx:1.9.5
          ports:
          - containerPort: 80
            protocol: TCP
